server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enableSelfPreservation: false   # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 5000  # 清理间隔（单位毫秒，默认是60*1000）