server:
  port: 8752
spring:
  profiles: peer2
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8751/eureka/
  server:
    enableSelfPreservation: false   # 设为false，关闭自我保护
    eviction-interval-timer-in-ms: 50000  # 清理间隔（单位毫秒，默认是60*1000）