eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
      lease-expiration-duration-in-seconds: 30 # 续约更新时间间隔（默认30秒）
      lease-renewal-interval-in-seconds: 10 # 续约到期时间（默认90秒）
server:
  port: 8767
spring:
  application:
    name: helloService
